package net.perfectdreams.flappyfuralha.webgl2

class GameResources(val resourceManager: ResourceManager) {
    val furalhaTextureId = resourceManager.loadTexture("furalha.png")
    val backdropTextureId = resourceManager.loadTexture("backdrop.png")
    val pipeTopId = resourceManager.loadTexture("pipe_top.png")
    val pipeBottomId = resourceManager.loadTexture("pipe_bottom.png")
    val groundId = resourceManager.loadTexture("ground.png")
    val tapId = resourceManager.loadTexture("tap.png")
    val getReadyId = resourceManager.loadTexture("get_ready.png")
    val flappyBirdLogoId = resourceManager.loadTexture("flappy_bird_logo.png")
    val gameOverId = resourceManager.loadTexture("game_over.png")
    val okButtonId = resourceManager.loadTexture("ok_button.png")
    val playButtonId = resourceManager.loadTexture("play_button.png")
    val scoreNumberZeroId = resourceManager.loadTexture("score_0.png")
    val scoreNumberOneId = resourceManager.loadTexture("score_1.png")
    val scoreNumberTwoId = resourceManager.loadTexture("score_2.png")
    val scoreNumberThreeId = resourceManager.loadTexture("score_3.png")
    val scoreNumberFourId = resourceManager.loadTexture("score_4.png")
    val scoreNumberFiveId = resourceManager.loadTexture("score_5.png")
    val scoreNumberSixId = resourceManager.loadTexture("score_6.png")
    val scoreNumberSevenId = resourceManager.loadTexture("score_7.png")
    val scoreNumberEightId = resourceManager.loadTexture("score_8.png")
    val scoreNumberNineId = resourceManager.loadTexture("score_9.png")
}